2019-02-02 17:12 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at 666
2019-02-02 20:17 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7ffb24c26948>
2019-02-02 20:17 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f754b044948>
2019-02-02 20:18 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f43213cf948>
2019-02-02 20:18 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7efdee750948>
2019-02-02 20:18 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7ffb08582948>
2019-02-02 20:19 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f977b601948>
2019-02-02 20:23 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f8d56f0d5e8>
2019-02-02 20:27 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f2411cb65e8>
2019-02-02 20:27 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f19c683b5e8>
2019-02-02 20:28 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f8ee03005e8>
2019-02-02 20:28 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f2a80a695e8>
2019-02-02 20:30 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f73522ff5e8>
2019-02-02 20:31 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7ff06f5619d8>
2019-02-02 20:34 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f7465501798>
2019-02-02 20:36 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f714cb74798>
2019-02-02 20:37 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7fbeefcae798>
2019-02-02 20:38 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f98e64c6708>
2019-02-02 20:38 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f66e55e5798>
2019-02-02 20:38 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7fe56be59798>
2019-02-02 20:39 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f7b5fa5f828>
2019-02-02 20:39 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f6832eaa798>
2019-02-02 20:39 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7facddfd6798>
2019-02-02 20:39 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7fb607f52798>
2019-02-02 20:40 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f8b1f4cb828>
2019-02-02 20:40 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f9fcc79f798>
2019-02-02 20:40 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f6d699ad708>
2019-02-02 20:40 - report_processer.py - process_csv_report - ERROR - Input file input is mocked does not exist
Could not process the file.
2019-02-02 20:42 - report_processer.py - process_csv_report - ERROR - Input file input is mocked does not exist
Could not process the file.
2019-02-02 20:43 - report_processer.py - process_csv_report - ERROR - Input file input is mocked does not exist
Could not process the file.
2019-02-02 20:44 - report_processer.py - process_csv_report - ERROR - Input file input is mocked does not exist
Could not process the file.
2019-02-02 20:45 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7fe9b8af5798>
2019-02-02 20:46 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f3f0ef63798>
2019-02-02 20:47 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f6c81fba798>
2019-02-02 20:48 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7ff88f118798>
2019-02-02 20:49 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7fc6615d9798>
2019-02-02 20:49 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7fe6b4c10798>
2019-02-02 20:49 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f0fa90a2798>
2019-02-02 20:49 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f5774a39828>
2019-02-02 20:50 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f42a9642798>
2019-02-02 20:52 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7fd56c78d828>
2019-02-02 20:52 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7fca39b428b8>
2019-02-02 20:52 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f6b619888b8>
2019-02-02 20:53 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7fe815f66828>
2019-02-02 20:53 - report_processer.py - _convert_data - ERROR - Row 11: Following CTR could not be converted: '0.68%das'
2019-02-02 20:53 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f67f0b31828>
2019-02-02 20:53 - report_processer.py - _convert_data - ERROR - Row 7: Following CTR could not be converted: '0.7%ads'
2019-02-02 20:53 - report_processer.py - _convert_data - ERROR - Row 9: Following CTR could not be converted: '0.1%asd'
2019-02-02 20:53 - report_processer.py - _convert_data - ERROR - Row 11: Following CTR could not be converted: '0.68%das'
2019-02-02 20:53 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7fabf7fc9828>
2019-02-02 20:55 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7fe2526da8b8>
2019-02-02 20:58 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f10710a58b8>
2019-02-02 20:59 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f80e6a118b8>
2019-02-02 20:59 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7fd14ce9e8b8>
2019-02-02 21:00 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f54b5724828>
2019-02-02 21:01 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f1b9385b8b8>
2019-02-02 21:01 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f3ca3b528b8>
2019-02-02 21:01 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7ff3bd3888b8>
2019-02-02 21:01 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7ff6cf6b18b8>
2019-02-02 21:02 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7fae9a3da8b8>
2019-02-02 21:02 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7fcdb62238b8>
2019-02-02 21:02 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f55eaeb08b8>
2019-02-02 21:09 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f6b644ae828>
2019-02-02 21:12 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f90cd6be678>
2019-02-02 21:13 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7eff1b8e9708>
2019-02-02 21:13 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7fdeb133c828>
2019-02-02 21:14 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7ff3db065678>
2019-02-02 21:14 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f683c4da8b8>
2019-02-02 21:14 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f53b1a6d828>
2019-02-02 21:15 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f88d42af828>
2019-02-02 21:16 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f0e9ec728b8>
2019-02-02 21:16 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7fa4a39ff828>
2019-02-02 21:18 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f085d58e708>
2019-02-02 21:18 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f541b74d828>
2019-02-02 21:18 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f1775379708>
2019-02-02 21:19 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f5cbd0b3708>
2019-02-02 21:19 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f5141d72708>
2019-02-02 21:48 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7fba760098b8>
2019-02-02 21:49 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7fd86b0d6828>
2019-02-02 21:49 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f6e5234b828>
2019-02-02 21:55 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 21:55 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f94231989d8>
2019-02-02 21:57 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 21:57 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f32a9a34a68>
2019-02-02 21:57 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f32c2a8bb88>
2019-02-02 21:58 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7fcb018f5a68>
2019-02-02 22:04 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-02 22:04 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f495af1daf8>
2019-02-02 22:04 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 22:04 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7fc9e4369a68>
2019-02-02 22:04 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 22:04 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:04 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:04 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:04 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:04 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:04 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:04 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:04 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:04 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:04 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:04 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:04 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:04 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-02 22:04 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7fc9e4369af8>
2019-02-02 22:04 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7fc9e43e0b88>
2019-02-02 22:04 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f900314aaf8>
2019-02-02 22:05 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 22:05 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7fc3359d2af8>
2019-02-02 22:05 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-02 22:05 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f41dee23af8>
2019-02-02 22:05 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 22:05 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f0ae329daf8>
2019-02-02 22:05 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 22:05 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f344e909a68>
2019-02-02 22:05 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 22:05 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:05 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:05 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:05 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:05 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:05 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:05 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:05 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:05 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:05 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:05 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:05 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:05 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-02 22:05 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f344e909af8>
2019-02-02 22:05 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f344e980b88>
2019-02-02 22:10 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 22:10 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f637e899b88>
2019-02-02 22:10 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 22:10 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:10 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:10 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:10 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:10 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:10 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:10 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:10 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:10 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:10 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:10 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:10 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:10 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-02 22:10 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f6397e77798>
2019-02-02 22:10 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f637e822af8>
2019-02-02 22:10 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-02 22:10 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7fa1a65a5af8>
2019-02-02 22:22 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7fb5656bdaf8>
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 22:22 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f68869eda68>

2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-02 22:22 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f68869edaf8>

2019-02-02 22:22 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f6886a64b88>
2019-02-02 22:22 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f18ea1eeaf8>
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 22:22 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f638199ca68>

2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-02 22:22 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f638199caf8>

2019-02-02 22:22 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f6381a13b88>
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 22:22 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7ffa8476ba68>

2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 22:22 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-02 22:22 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7ffa8476baf8>

2019-02-02 22:22 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7ffa847e2b88>
2019-02-02 23:07 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:07 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f22082dc9d8>
2019-02-02 23:07 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:07 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:07 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:07 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:07 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:07 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:07 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:07 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:07 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:07 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:07 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:07 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:07 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:07 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f22082dcc18>
2019-02-02 23:07 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-02 23:07 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f2207c1d288>
2019-02-02 23:07 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7fcec69bca68>
2019-02-02 23:07 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:07 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f99ef3d8a68>
2019-02-02 23:08 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f19721f5a68>
2019-02-02 23:08 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f6ef83e1a68>
2019-02-02 23:11 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f9396fb9a68>
2019-02-02 23:11 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:11 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7ff7445aaa68>
2019-02-02 23:12 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:12 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f04f4eeda68>
2019-02-02 23:12 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:12 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f0ff89e8a68>
2019-02-02 23:13 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:13 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fa514289a68>
2019-02-02 23:13 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-02 23:13 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:13 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7ffaac7eaa68>
2019-02-02 23:13 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-02 23:14 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-02 23:17 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-02 23:17 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fb193d44a68>
2019-02-02 23:17 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:17 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fe9b004aa68>
2019-02-02 23:18 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f47dd1eda68>
2019-02-02 23:18 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:18 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fe8cc550a68>
2019-02-02 23:18 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-02 23:18 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f458a13ca68>
2019-02-02 23:19 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-02 23:19 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f98acc380d8>
2019-02-02 23:20 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-02 23:20 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f869a0200d8>
2019-02-02 23:20 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-02 23:20 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f91bd0810d8>
2019-02-02 23:21 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-02 23:21 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f6a6f9410d8>
2019-02-02 23:21 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:21 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f81612300d8>
2019-02-02 23:22 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:22 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f05e5af9168>
2019-02-02 23:22 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f05cdd02558>
2019-02-02 23:22 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:22 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f3c313090d8>
2019-02-02 23:22 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f3c196f44c8>
2019-02-02 23:23 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:23 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fc7cbc130d8>
2019-02-02 23:23 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7fc7b3fb74c8>
2019-02-02 23:23 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:23 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7ffa2ce44a68>
2019-02-02 23:23 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7ffa44cfd1f8>
2019-02-02 23:23 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:23 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:23 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:23 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:23 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:23 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:23 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:23 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:23 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:23 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:23 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:23 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:23 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:23 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7ffa2ce464c8>
2019-02-02 23:23 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-02 23:23 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7ffa44cfd0d8>
2019-02-02 23:23 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7ffa44cfd1f8>
2019-02-02 23:24 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7fab9b34f0d8>
2019-02-02 23:24 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:24 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fb0924ea0d8>
2019-02-02 23:24 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-02 23:24 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f4c67bc70d8>
2019-02-02 23:24 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:24 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f4c255680d8>
2019-02-02 23:24 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f4c0d90c4c8>
2019-02-02 23:24 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:24 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f28c71e3ee8>
2019-02-02 23:24 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-02 23:24 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f28c71e3a68>
2019-02-02 23:24 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f28ae1378b8>
2019-02-02 23:25 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:25 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f739498aa68>
2019-02-02 23:25 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f7394ea54c8>
2019-02-02 23:25 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:25 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fafda9738b8>
2019-02-02 23:25 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7faff39ffa68>
2019-02-02 23:25 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:25 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f3ae0eca948>
2019-02-02 23:25 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f3af9fb8af8>
2019-02-02 23:25 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-02 23:25 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f3ae0ece3a8>
2019-02-02 23:25 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:25 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7efdf6c8daf8>
2019-02-02 23:25 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7efdf7173678>
2019-02-02 23:25 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-02 23:25 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7efdf5b730d8>
2019-02-02 23:25 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:25 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f167832d9d8>
2019-02-02 23:25 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f1690348168>
2019-02-02 23:25 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:25 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:25 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:25 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:25 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:25 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:25 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:25 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:25 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:25 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:25 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:25 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:25 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:25 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f1678330438>
2019-02-02 23:25 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-02 23:25 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f1690348048>
2019-02-02 23:25 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:25 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fa21d697dc8>
2019-02-02 23:25 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:25 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f718098fdc8>
2019-02-02 23:25 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:25 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fbbde18df78>
2019-02-02 23:25 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7fbbde6735e8>
2019-02-02 23:26 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:26 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f4ae4576048>
2019-02-02 23:26 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-02 23:26 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f4ae5e354c8>
2019-02-02 23:26 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f4ae5908a68>
2019-02-02 23:26 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:26 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f13ee5f9f78>
2019-02-02 23:26 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f13ed5250d8>
2019-02-02 23:26 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:26 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:26 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:26 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:26 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:26 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:26 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:26 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:26 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:26 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:26 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:26 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:26 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:26 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f13eeb24678>
2019-02-02 23:26 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-02 23:26 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f13ee5f9af8>
2019-02-02 23:26 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f13ed5250d8>
2019-02-02 23:28 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:28 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f171713c1f8>
2019-02-02 23:28 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f171883b798>
2019-02-02 23:28 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:28 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:28 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:28 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:28 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:28 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:28 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:28 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:28 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:28 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:28 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:28 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:28 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:28 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f171713c0d8>
2019-02-02 23:28 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-02 23:28 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f171834ec18>
2019-02-02 23:28 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f171883b798>
2019-02-02 23:28 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:28 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fb764a43168>
2019-02-02 23:28 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7fb76603e708>
2019-02-02 23:28 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-02 23:28 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fb764a43048>
2019-02-02 23:28 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7fb765d35b88>
2019-02-02 23:29 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:29 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f1dc82c70d8>
2019-02-02 23:30 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:30 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f1bdd533a68>
2019-02-02 23:30 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f1bf53eb1f8>
2019-02-02 23:30 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:30 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:30 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:30 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:30 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:30 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:30 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:30 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:30 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:30 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:30 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:30 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:30 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:30 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f1bdd5354c8>
2019-02-02 23:30 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-02 23:30 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f1bf53eb0d8>
2019-02-02 23:30 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f1bf53eb1f8>
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:33 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7face6a0ba68>
2019-02-02 23:33 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7facfe8c51f8>
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7face6a0d4c8>
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-02 23:33 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7facfe8c50d8>
2019-02-02 23:33 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7facfe8c51f8>
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:33 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f8f82042168>
2019-02-02 23:33 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f8f83741708>
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f8f82042048>
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-02 23:33 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f8f83215b88>
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:33 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fcf6948eaf8>
2019-02-02 23:33 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7fcf69975678>
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-02 23:33 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fcf683b40d8>
2019-02-02 23:33 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-02 23:33 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f9e474f2a68>
2019-02-03 09:33 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 09:33 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f648f9008b8>
2019-02-03 09:33 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 09:33 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f8bf7a2b948>
2019-02-03 09:33 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f8c10ad7af8>
2019-02-03 09:33 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 09:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:33 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:33 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f8bf7a2f3a8>
2019-02-03 09:37 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 09:37 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f79dfefde58>
2019-02-03 09:37 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f79c6ea70d8>
2019-02-03 09:37 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 09:37 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:37 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:37 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:37 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:37 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:37 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:37 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:37 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:37 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:37 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:37 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:37 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:37 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f79dfefd9d8>
2019-02-03 09:40 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 09:40 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fd522a29f78>
2019-02-03 09:40 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7fd522a29e58>
2019-02-03 09:40 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 09:40 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:40 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:40 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:40 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:40 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:40 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:40 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:40 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:40 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:40 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:40 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:40 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:40 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fd522f145e8>
2019-02-03 09:42 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 09:42 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f4213030f78>
2019-02-03 09:42 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f4213030e58>
2019-02-03 09:42 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 09:42 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:42 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:42 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:42 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:42 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:42 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:42 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:42 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:42 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:42 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:42 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:42 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:42 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f42134855e8>
2019-02-03 09:43 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 09:43 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f6ca2038f78>
2019-02-03 09:43 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f6ca2038e58>
2019-02-03 09:43 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 09:43 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:43 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:43 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:43 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:43 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:43 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:43 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:43 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:43 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:43 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:43 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:43 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:43 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f6ca24125e8>
2019-02-03 09:45 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 09:45 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fbe52cccf78>
2019-02-03 09:45 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7fbe52ccce58>
2019-02-03 09:45 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 09:45 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:45 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:45 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:45 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:45 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:45 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:45 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:45 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:45 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:45 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:45 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:45 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 09:45 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fbe530a35e8>
2019-02-03 09:49 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 09:50 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fc8f9882288>
2019-02-03 09:50 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7fc8f9861708>
2019-02-03 10:14 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 10:14 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fab8db4f708>
2019-02-03 10:15 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 10:15 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fd927567ee8>
2019-02-03 10:16 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 10:16 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f9d10fccee8>
2019-02-03 10:16 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 10:16 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f73ff63ef78>
2019-02-03 10:16 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f73ff63ee58>
2019-02-03 10:16 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 10:16 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:16 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:16 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:16 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:16 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:16 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:16 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:16 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:16 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:16 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:16 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:16 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:16 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f73ffb685e8>
2019-02-03 10:17 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 10:17 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fa96ac0cf78>
2019-02-03 10:17 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7fa96ac0ce58>
2019-02-03 10:17 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 10:17 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:17 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:17 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:17 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:17 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:17 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:17 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:17 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:17 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:17 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:17 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:17 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:17 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fa96c6335e8>
2019-02-03 10:18 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 10:18 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f2f90e64f78>
2019-02-03 10:18 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f2f90e64e58>
2019-02-03 10:18 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 10:18 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:18 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:18 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:18 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:18 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:18 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:18 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:18 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:18 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:18 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:18 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:18 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:18 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f2f9290a5e8>
2019-02-03 10:18 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 10:18 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fc5452c1e58>
2019-02-03 10:18 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 10:18 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fb548003f78>
2019-02-03 10:18 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7fb548003e58>
2019-02-03 10:18 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 10:18 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:18 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:18 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:18 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:18 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:18 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:18 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:18 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:18 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:18 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:18 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:18 - report_processer.py - _convert_data - ERROR - 'int' object has no attribute 'rstrip'
2019-02-03 10:18 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fb5483df5e8>
2019-02-03 10:19 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 10:19 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f46aa7edf78>
2019-02-03 10:19 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f46aa7ede58>
2019-02-03 10:19 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 10:19 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f46aabc65e8>
2019-02-03 10:20 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 10:20 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f89c6296ee8>
2019-02-03 10:20 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f89c6296e58>
2019-02-03 10:20 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 10:20 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f89c67be5e8>
2019-02-03 10:22 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 10:22 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f34853f4e58>
2019-02-03 10:22 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 10:22 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fbbea3bbee8>
2019-02-03 10:22 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 10:22 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fbbea8a65e8>
2019-02-03 10:23 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 10:23 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fc40334ff78>
2019-02-03 10:23 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7fc40334fee8>
2019-02-03 10:23 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 10:23 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fc4038355e8>
2019-02-03 10:24 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 10:24 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f411a4c81f8>
2019-02-03 10:24 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f411a8ce798>
2019-02-03 10:24 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 10:24 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f411a4c8168>
2019-02-03 10:24 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 10:24 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f411a405ca8>
2019-02-03 10:24 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f411a8ce798>
2019-02-03 10:45 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f26785acd38>
2019-02-03 10:50 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f96f333fd38>
2019-02-03 10:50 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 10:50 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f96f4d4d678>
2019-02-03 10:51 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f40397e74c8>
2019-02-03 10:51 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 10:51 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f403af05678>
2019-02-03 10:51 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 10:51 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f40394f7dc8>
2019-02-03 10:51 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7ff36dc538b8>
2019-02-03 10:51 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 10:51 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7ff36df4f438>
2019-02-03 10:51 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 10:51 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7ff35604a288>
2019-02-03 10:51 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 10:51 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7ff35604ae58>
2019-02-03 10:55 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f09d1816438>
2019-02-03 10:55 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 10:55 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f09d2f73678>
2019-02-03 10:55 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 10:55 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f09d161e8b8>
2019-02-03 10:55 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 10:55 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f09b9995288>
2019-02-03 10:55 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f09d1564d38>
2019-02-03 11:18 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 11:18 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fe7bf53a558>
2019-02-03 11:18 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7fe7bf2890d8>
2019-02-03 11:18 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7fe7c0cf95e8>
2019-02-03 11:18 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 11:18 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fe7bf289e58>
2019-02-03 11:18 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 11:18 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fe7bf2890d8>
2019-02-03 11:18 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 11:18 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f6c8ab1bee8>
2019-02-03 11:18 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f6c72e9be58>
2019-02-03 11:18 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f6c8ab1b168>
2019-02-03 11:18 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 11:18 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f6c8c08f5e8>
2019-02-03 11:18 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 11:18 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f6c72e9be58>
2019-02-03 11:21 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 11:21 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f10f4c9eee8>
2019-02-03 11:21 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f10dd05ee58>
2019-02-03 11:21 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f10dcfe5af8>
2019-02-03 11:21 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 11:21 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f10f62115e8>
2019-02-03 11:21 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 11:21 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f10dcabcca8>
2019-02-03 11:21 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 11:21 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f10dcfe5af8>
2019-02-03 11:22 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f4ccc4e8e58>
2019-02-03 11:22 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 11:22 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f4ccc7da558>
2019-02-03 11:22 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 11:22 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f4ccde5b4c8>
2019-02-03 11:22 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 11:22 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f4cb4898dc8>
2019-02-03 11:22 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 11:22 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f2a8ed93ee8>
2019-02-03 11:22 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f2a77153e58>
2019-02-03 11:22 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f2a770daaf8>
2019-02-03 11:22 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 11:22 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f2a903085e8>
2019-02-03 11:22 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 11:22 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f2a76b72ca8>
2019-02-03 11:22 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 11:22 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f2a770daaf8>
2019-02-03 11:23 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 11:23 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f1dfd3f6ee8>
2019-02-03 11:23 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f1de57b6e58>
2019-02-03 11:23 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f1de573daf8>
2019-02-03 11:23 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 11:23 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f1dfe96a5e8>
2019-02-03 11:23 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 11:23 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f1de57b6e58>
2019-02-03 11:23 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 11:23 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f1de573daf8>
2019-02-03 11:25 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 11:25 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f795445cee8>
2019-02-03 11:25 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f793c85ae58>
2019-02-03 11:25 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 11:25 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f793c7e1af8>
2019-02-03 11:25 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f793c2b8828>
2019-02-03 11:25 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 11:25 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f7955b4f5e8>
2019-02-03 11:25 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f793c2b8e58>
2019-02-03 11:25 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f793c85ae58>
2019-02-03 11:25 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 11:25 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f793c2b8d38>
2019-02-03 11:25 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 11:25 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f793c2b8f78>
2019-02-03 11:25 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 11:25 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f793c85ae58>
2019-02-03 11:26 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f132beede58>
2019-02-03 11:26 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 11:26 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f132c25d558>
2019-02-03 11:26 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 11:26 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f132d8db4c8>
2019-02-03 11:26 - report_processer.py - _convert_data - ERROR - Row 0: Following CTR could not be converted: '0.3asd8'
2019-02-03 11:26 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f13142eadc8>
2019-02-03 11:27 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7fe05db2ce58>
2019-02-03 11:27 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 11:27 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fe05f08d558>
2019-02-03 11:27 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 11:27 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fe05f49c4c8>
2019-02-03 11:27 - report_processer.py - _convert_data - ERROR - Row 0: Following CTR could not be converted: '0.3asd8'
2019-02-03 11:27 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fe045eaadc8>
2019-02-03 11:28 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f305dabde58>
2019-02-03 11:28 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 11:28 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f305f02f558>
2019-02-03 11:28 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 11:28 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f305f42d4c8>
2019-02-03 11:28 - report_processer.py - _convert_data - ERROR - Row 0: Following CTR could not be converted: '0.3asd8'
2019-02-03 11:28 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f3045e7cdc8>
2019-02-03 11:45 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7fde830ede58>
2019-02-03 11:45 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 11:45 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fde8475f558>
2019-02-03 11:45 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 11:45 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fde84a5c4c8>
2019-02-03 11:45 - report_processer.py - _convert_data - ERROR - Row 0: Following CTR could not be converted: '0.3asd8'
2019-02-03 11:45 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fde6b46bdc8>
2019-02-03 11:46 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 11:46 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f7743f63ee8>
2019-02-03 11:46 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f772ac5ee58>
2019-02-03 11:46 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 11:46 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f772abe5af8>
2019-02-03 11:46 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f772a607828>
2019-02-03 11:46 - report_processer.py - _convert_data - ERROR - Row 0: Following CTR could not be converted: '0.3asd8'
2019-02-03 11:46 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f7742bd35e8>
2019-02-03 11:46 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f772a607ee8>
2019-02-03 11:46 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f772ac5ee58>
2019-02-03 11:46 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 11:46 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f772a607dc8>
2019-02-03 11:46 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 11:46 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f772a2f4048>
2019-02-03 11:46 - report_processer.py - _convert_data - ERROR - Row 0: Following CTR could not be converted: '0.3asd8'
2019-02-03 11:46 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f772ac5ee58>
2019-02-03 11:47 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 11:47 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f7aa0434ee8>
2019-02-03 11:47 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f7a88832e58>
2019-02-03 11:47 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f7a887b9af8>
2019-02-03 11:47 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 11:47 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f7aa07a65e8>
2019-02-03 11:47 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 11:47 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f7a88832e58>
2019-02-03 11:47 - report_processer.py - _convert_data - ERROR - Row 0: Following CTR could not be converted: '0.3asd8'
2019-02-03 11:47 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f7a887b9af8>
2019-02-03 11:47 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 11:47 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fde44483ee8>
2019-02-03 11:47 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7fde2c881e58>
2019-02-03 11:47 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 11:47 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fde2c808af8>
2019-02-03 11:47 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7fde2c263828>
2019-02-03 11:47 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7fde447f45e8>
2019-02-03 11:47 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 11:47 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fde2c881e58>
2019-02-03 11:47 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 11:47 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fde2c263dc8>
2019-02-03 11:47 - report_processer.py - _convert_data - ERROR - Row 0: Following CTR could not be converted: '0.3asd8'
2019-02-03 11:47 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fde2c263ee8>
2019-02-03 11:48 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 11:48 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f8cd4365ee8>
2019-02-03 11:48 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f8cbc760e58>
2019-02-03 11:48 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 11:48 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f8cbc6e7af8>
2019-02-03 11:48 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f8cbc107828>
2019-02-03 11:48 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f8cd46d45e8>
2019-02-03 11:48 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 11:48 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f8cbc760e58>
2019-02-03 11:48 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 11:48 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f8cbc6e7af8>
2019-02-03 11:48 - report_processer.py - _convert_data - ERROR - Row 0: Following CTR could not be converted: '0.3asd8'
2019-02-03 11:48 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f8cd46d45e8>
2019-02-03 11:48 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 11:48 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f4797531ee8>
2019-02-03 11:48 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f477e36ce58>
2019-02-03 11:48 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 11:48 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f477e2f3af8>
2019-02-03 11:48 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f477dd4e828>
2019-02-03 11:48 - report_processer.py - _convert_data - ERROR - Row 0: Following CTR could not be converted: '0.3asd8'
2019-02-03 11:48 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f47962a05e8>
2019-02-03 11:48 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f477dd4e8b8>
2019-02-03 11:48 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f477e36ce58>
2019-02-03 11:48 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 11:48 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f477e2f3af8>
2019-02-03 11:48 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 11:48 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f477dd4eee8>
2019-02-03 11:48 - report_processer.py - _convert_data - ERROR - Row 0: Following CTR could not be converted: '0.3asd8'
2019-02-03 11:48 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f477e36ce58>
2019-02-03 11:49 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 11:49 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fcf617f8ee8>
2019-02-03 11:49 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7fcf48533e58>
2019-02-03 11:49 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 11:49 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fcf484baaf8>
2019-02-03 11:49 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7fcf47f13828>
2019-02-03 11:49 - report_processer.py - _convert_data - ERROR - Row 0: Following CTR could not be converted: '0.3asd8'
2019-02-03 11:49 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fcf604a85e8>
2019-02-03 11:49 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7fcf47f138b8>
2019-02-03 11:49 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7fcf48533e58>
2019-02-03 11:49 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 11:49 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fcf484baaf8>
2019-02-03 11:49 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 11:49 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fcf604a85e8>
2019-02-03 11:49 - report_processer.py - _convert_data - ERROR - Row 0: Following CTR could not be converted: '0.3asd8'
2019-02-03 11:49 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7fcf48533e58>
2019-02-03 11:49 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 11:49 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7ff2afa7b708>
2019-02-03 11:49 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7ff2afa15828>
2019-02-03 11:49 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 11:49 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7ff2afa7b438>
2019-02-03 11:49 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7ff2af521948>
2019-02-03 11:49 - report_processer.py - _convert_data - ERROR - Row 0: Following CTR could not be converted: '0.3asd8'
2019-02-03 11:49 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7ff2afa01af8>
2019-02-03 11:49 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7ff2af5219d8>
2019-02-03 11:49 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7ff2afa15828>
2019-02-03 11:49 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 11:49 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7ff2afa7b438>
2019-02-03 11:49 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 11:49 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7ff2afa01af8>
2019-02-03 11:49 - report_processer.py - _convert_data - ERROR - Row 0: Following CTR could not be converted: '0.3asd8'
2019-02-03 11:49 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7ff2afa15828>
2019-02-03 11:52 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 11:52 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f8859364ee8>
2019-02-03 11:52 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f88401dfe58>
2019-02-03 11:52 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 11:52 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f8840166af8>
2019-02-03 11:52 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f883fbc2828>
2019-02-03 11:52 - report_processer.py - _convert_data - ERROR - Row 0: Following CTR could not be converted: '0.3asd8'
2019-02-03 11:52 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f8857dd45e8>
2019-02-03 11:52 - report_processer.py - process_csv_report - INFO - Invalid data has been excluded from the result and saved at <_io.StringIO object at 0x7f883fbc28b8>
2019-02-03 11:52 - report_processer.py - process_csv_report - INFO - File has been converted without errors and saved at <_io.StringIO object at 0x7f88401dfe58>
2019-02-03 11:52 - report_processer.py - _convert_data - ERROR - Row 0: Following date could not be converted: 0sad1/21/2019

2019-02-03 11:52 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f8840166af8>
2019-02-03 11:52 - report_processer.py - _convert_data - ERROR - Row 0: Following impression number could not be converted: '88asd3'
2019-02-03 11:52 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f8857dd45e8>
2019-02-03 11:52 - report_processer.py - _convert_data - ERROR - Row 0: Following CTR could not be converted: '0.3asd8'
2019-02-03 11:52 - report_processer.py - process_csv_report - INFO - File has been converted with errors and saved at <_io.StringIO object at 0x7f88401dfe58>
